In [3]:
import pandas as pd
sales_data = {
    "Store": [
        "Manchester", "London", "Leeds", "Manchester", "London",
        "Leeds", "Manchester", "London", "Leeds", "Manchester"
    ],
    "Region": [
        "North", "South", "North", "North", "South",
        "North", "North", "South", "North", "North"
    ],
    "Product": [
        "Laptop", "Phone", "Headphones", "Phone", "Laptop",
        "Mouse", "Keyboard", "Phone", "Laptop", "Mouse"
    ],
    "Quantity": [
        2, 3, 5, 1, 2,
        4, 3, 2, 1, 6
    ],
    "Price": [
        800, 500, 80, 500, 800,
        25, 50, 500, 800, 25
    ]
}

In [4]:
sales = pd.DataFrame(sales_data)

sales

        Store Region     Product  Quantity  Price
0  Manchester  North      Laptop         2    800
1      London  South       Phone         3    500
2       Leeds  North  Headphones         5     80
3  Manchester  North       Phone         1    500
4      London  South      Laptop         2    800
5       Leeds  North       Mouse         4     25
6  Manchester  North    Keyboard         3     50
7      London  South       Phone         2    500
8       Leeds  North      Laptop         1    800
9  Manchester  North       Mouse         6     25

In [5]:
sales["Revenue"] = sales["Quantity"] * sales["Price"]

sales

        Store Region     Product  Quantity  Price  Revenue
0  Manchester  North      Laptop         2    800     1600
1      London  South       Phone         3    500     1500
2       Leeds  North  Headphones         5     80      400
3  Manchester  North       Phone         1    500      500
4      London  South      Laptop         2    800     1600
5       Leeds  North       Mouse         4     25      100
6  Manchester  North    Keyboard         3     50      150
7      London  South       Phone         2    500     1000
8       Leeds  North      Laptop         1    800      800
9  Manchester  North       Mouse         6     25      150

In [6]:
store_revenue = sales.groupby("Store")["Revenue"].sum()

store_revenue

Store
Leeds         1300
London        4100
Manchester    2400
Name: Revenue, dtype: int64

In [7]:
store_revenue = sales.groupby("Store")["Revenue"].sum()

store_revenue

Store
Leeds         1300
London        4100
Manchester    2400
Name: Revenue, dtype: int64

In [8]:
sales.groupby("Product")["Revenue"].sum()

Product
Headphones     400
Keyboard       150
Laptop        4000
Mouse          250
Phone         3000
Name: Revenue, dtype: int64

In [9]:
sales.groupby("Region")["Revenue"].sum()

Region
North    3700
South    4100
Name: Revenue, dtype: int64

In [10]:
store_revenue = sales.groupby("Store")["Revenue"].sum()

store_revenue = store_revenue.sort_values(ascending=False)

store_revenue

Store
London        4100
Manchester    2400
Leeds         1300
Name: Revenue, dtype: int64

In [11]:
product_revenue = sales.groupby("Product")["Revenue"].sum()

product_revenue.sort_values(ascending=False)

Product
Laptop        4000
Phone         3000
Headphones     400
Mouse          250
Keyboard       150
Name: Revenue, dtype: int64

In [12]:
product_revenue.sort_values(ascending=True)

Product
Keyboard       150
Mouse          250
Headphones     400
Phone         3000
Laptop        4000
Name: Revenue, dtype: int64

In [13]:
sales["Revenue"].mean()

780.0

In [14]:
sales.groupby("Store")["Store"].count()

Store
Leeds         3
London        3
Manchester    4
Name: Store, dtype: int64

In [15]:
sales["Revenue"].max()

1600

In [16]:
sales["Revenue"].min()

100

In [17]:
total_revenue = sales["Revenue"].sum()

average_revenue = sales["Revenue"].mean()

highest_sale = sales["Revenue"].max()

lowest_sale = sales["Revenue"].min()

In [18]:
print("Total Revenue:", total_revenue)
print("Average Revenue:", average_revenue)
print("Highest Sale:", highest_sale)
print("Lowest Sale:", lowest_sale)

Total Revenue: 7800
Average Revenue: 780.0
Highest Sale: 1600
Lowest Sale: 100

In [22]:
summary = pd.DataFrame({
    "Business Question": [
        "Total Revenue",
        "Average Revenue",
        "Highest Sale",
        "Lowest Sale"
    ],
    "Answer": [
        total_revenue,
        average_revenue,
        highest_sale,
        lowest_sale
    ]
})

summary

  Business Question  Answer
0     Total Revenue  7800.0
1   Average Revenue   780.0
2      Highest Sale  1600.0
3       Lowest Sale   100.0

In [23]:
highest_store = sales.groupby("Store")["Revenue"].sum().idxmax()

highest_product = sales.groupby("Product")["Revenue"].sum().idxmax()

highest_region = sales.groupby("Region")["Revenue"].sum().idxmax()

busiest_store = sales.groupby("Store")["Store"].count().idxmax()

In [24]:
summary = pd.DataFrame({
    "Business Question": [
        "Total Revenue",
        "Average Revenue",
        "Highest Sale",
        "Lowest Sale",
        "Highest Revenue Store",
        "Highest Revenue Product",
        "Highest Revenue Region",
        "Store With Most Sales"
    ],
    "Answer": [
        total_revenue,
        average_revenue,
        highest_sale,
        lowest_sale,
        highest_store,
        highest_product,
        highest_region,
        busiest_store
    ]
})

summary

         Business Question      Answer
0            Total Revenue        7800
1          Average Revenue       780.0
2             Highest Sale        1600
3              Lowest Sale         100
4    Highest Revenue Store      London
5  Highest Revenue Product      Laptop
6   Highest Revenue Region       South
7    Store With Most Sales  Manchester

In [25]:
summary.to_csv("output/retail_sales_summary.csv", index=False)